### PR TITLE
[add] search tag cloud and filtering feature 

### PR DESCRIPTION
**Pull request by andyttran**

### CODE REVIEW

**Comment by dgrundfest** [comment]
This looks good. @andyttran will we be able to incorporate the search directive in the tagging module?

**Comment by andyttran** [comment]
@dgrundfest yes I will have to modify the directive to remove the isolate scope and then move the directive to a shared directory for other controllers to use.

**Comment by dgrundfest** [comment]
@andyttran awesome

**Comment by vtumrukota** [comment]
Great work Andy

**Pull request merged**
